In [1]:
import numpy as np

In [17]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [18]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
arr.shape

(3, 4)

In [8]:
arr.size

12

In [9]:
arr.ndim

2

In [5]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
arr[0,] # Accessing 1st row of the array by array slicing
# 1st argument is for the the index of row and second argument is none because we have to access row only

array([1, 2, 3, 4])

In [13]:
# We can access the element at the third row and fourth column from the given numpy array by the following code
arr[2][3]

12

In [5]:
# To extract all odd-indexed elements from the given numpy array , following array slicing can be done
arr[0:3,[1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [12]:
# We can generate a random 3x3 matrix with values between 0 and 1 by the following numpy function

arr2 = np.random.rand(3,3)

In [13]:
arr2

array([[0.98404434, 0.07066272, 0.46165573],
       [0.94369571, 0.84697087, 0.12581216],
       [0.10301535, 0.44380971, 0.26942897]])

In [3]:
np.random.rand(3,3) # All generated random numbers are from 0-1

array([[0.13326121, 0.03535223, 0.30576647],
       [0.8856486 , 0.11849164, 0.97780771],
       [0.83120083, 0.94824378, 0.53136459]])

In [4]:
np.random.randn(3,3)

array([[ 0.01969729, -0.01739279,  0.32630199],
       [ 0.18534289,  0.09252909,  0.17213531],
       [-1.10766736, -0.83793255,  0.86214542]])

In [4]:
arr_1 = np.expand_dims(arr,axis = 0)

In [5]:
arr_1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [6]:
# We can transpose the following array in NumPy by following code
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [11]:
Matrix_A = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_B = np.array([[1, 2, 3, 4] , [5, 6, 7, 8],[9, 10, 11, 12]])

In [22]:
# 1. Index wise multiplication 
Matrix_A * Matrix_B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [25]:
# 2. Matrix multiplication

'''
We cant do matrix multiplication because shape of Matrix A is 3X4 and shape of Maztrix B is also 3X4,
Matrix of order pXq and mXn can only get multiplied if q = m 
here, 4 is not equal to 3 therefore we cannot do matrix multiplication
'''

# But we can do matrix multiplication by tramnsposing one of the 2 matrix

T_Matraix_B = Matrix_B.T

In [26]:
Matrix_A @ T_Matraix_B

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [28]:
# 3. Add both the matrices
Matrix_A + Matrix_B # This is index wise addition

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [29]:
# 4. Subtact matrix B from A 
Matrix_B - Matrix_A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
# 5. Divide Matrix B by A
Matrix_B/Matrix_A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
arr.byteswap(True)
# This change the byte order of array

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

In [5]:
# Sorry i dont know about it but i will surely understand it very soon

In [21]:
arr.shape # Multiplication of its shape  = 12

(3, 4)

In [22]:
arr.reshape(4,3) # Here , multiplication is still 12 therefore we can reshape it

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
arr.reshape(6,2)  # Here also, multiplication is still 12 therefore we can reshape it

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [24]:
arr.reshape(2,7) # This will show error because multiplication of 2 and 7 is not equal to 12

ValueError: cannot reshape array of size 12 into shape (2,7)

In [25]:
# For exa.

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr + 1 # Here every element is getting added by 1 , hence it is known as broadcasting

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [28]:
# one more example
arr/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])